
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbxltdbnqixucjoognfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieGx0ZGJucWl4dWNqb29nbmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDQxMDksImV4cCI6MjA2MTcyMDEwOX0.ZsH2LX5JVFk7tCC0gGmjP1ZrVlQJ78nSUlMqxW7L1rw";

const getAccessToken = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) throw new Error('No authentication session');

  if (session.expires_at && session.expires_at * 1000 <= Date.now() + 60_000) {
    const { data, error } = await supabase.auth.refreshSession();
    if (error || !data.session) throw new Error('Authentication session expired');
    return data.session.access_token;
  }

  return session.access_token;
};

const requestAdminAPI = async (path = '', init: RequestInit = {}) => {
  const accessToken = await getAccessToken();
  const response = await fetch(`${SUPABASE_URL}/functions/v1/admin-users${path}`, {
    ...init,
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
      ...init.headers,
    },
  });

  return await response.json();
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Secure admin API that calls edge functions instead of exposing service role key
export const adminAPI = {
  async listUsers() {
    return await requestAdminAPI('', {
      method: 'GET',
    });
  },

  async createUser(userData: { email: string; password: string; name: string; role: string }) {
    return await requestAdminAPI('', {
      method: 'POST',
      body: JSON.stringify(userData),
    });
  },

  async updateUserById(userId: string, userData: any) {
    return await requestAdminAPI(`/${userId}`, {
      method: 'PUT',
      body: JSON.stringify(userData),
    });
  },

  async deleteUser(userId: string) {
    return await requestAdminAPI(`/${userId}`, {
      method: 'DELETE',
    });
  },

  async getUserById(userId: string) {
    return await requestAdminAPI(`/${userId}`, {
      method: 'GET',
    });
  }
};
